env:
  AUTH0_TEST_CLIENT_ID: ENCRYPTED[d0d0556878f5f1a96ae8167b6ee8fbb74f283f810bd18bac775d0aae722b86669111b567f6ae13e220d502ea44bd4037]
  AUTH0_TEST_CLIENT_SECRET: ENCRYPTED[8a5c05a26564fff83259686bb2d9b5092561137586660df5974e3eb868e620d19c56b402f5ea9989d227f15e9062b56c]
  AUTH0_USER_MGMT_CLIENT_ID: ENCRYPTED[91cc07f55e10dbe7b26bca01f68efccf94eaab7cb0eda0f529b4210b684a698ad76c677d93c82d48b54e5176ebcfadf5]
  AUTH0_USER_MGMT_CLIENT_SECRET: ENCRYPTED[21ed2fa8098c25532331e2b5a580c4a3939222b37ae2bc6a5bc23287652cf656efd537b80811bc678dafa22a137682cb]
  AUTH0_VOLUBLE_TENANT: "voluble-dev.eu.auth0.com"
  AUTH0_API_ID: "https://voluble-poc.herokuapp.com"
  AUTH0_PROXY_ALLOWED_ORIGINS: "http://lvh.me:4200;https://voluble-poc.herokuapp.com;https://cirrus-ci.com;https://cirrus-ci.org"
  CLEARDB_DATABASE_URL: "mysql://voluble_test:volubletest@127.0.0.1/voluble_test"
  ESENDEX_ACCOUNT_REF: ENCRYPTED[1923dae4c399adb1241938870ca0ad18c23ef223499392509a5c180dce85310d3c9c400eff9b73b0c28f1fe34da9fa95]
  ESENDEX_PASSWORD: ENCRYPTED[413453ac5604edf2f6969411da3ab3af118e19a962644b2a46928f8807d50ddbba086029e2b83eb969ffa5192c186142]
  ESENDEX_USERNAME: ENCRYPTED[d476d309b6f11ebe02b8bbd69123f6a4b9c01763120d9184b95715a6b8416eda67a53a973fb8857bfec96cc97019530e]
  PLUGIN_DIR: "bin/plugins"
  REDISTOGO_URL: ENCRYPTED[c4e9f4c3638091c2bd6ceae48251a6584de1bf2a4db62cf90005f35a24e70123bd405e289d86a1171704b055403735ab]
  NODE_ENV: "development"
  PORT: 5000
  GIT_ACCESS_TOKEN: ENCRYPTED[e73dca0e2a214b435158ee1dc0b4913b1fe319f2b7de8c28e57130bb042395e029ba3fab47d62331473585ec54695d76]

container:
  image: node:latest
  additional_containers:
    - name: mysql
      image: mysql:5 #MySQL 8 has password issues with 'caching-sha2-password' plugin
      port: 3306
      cpu: 1.0
      memory: 512Mi
      env:
        MYSQL_ROOT_PASSWORD: "pa55w0rd"

test_task:
  global_clis_script:
    - npm install -g typescript mocha
    - apt update
    - apt install mysql-client -y

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script:
      - cp package-lock.json cp package-lock.json.bkp
      - sed -i "s/git+https:\/\/github\.com\/CrewText/git+https:\/\/${GIT_ACCESS_TOKEN}:x-oauth-basic@github\.com\/CrewText/g" package-lock.json
      - npm ci
      - rm package-lock.json
      - cp package-lock.json.bkp package-lock.json

  build_script:
    - tsc -v;
    - tsc

  mysql_setup_script:
    - mysql -uroot -ppa55w0rd -P3306 -h127.0.0.1 -e "CREATE DATABASE voluble_test;"
    - mysql -uroot -ppa55w0rd -P3306 -h127.0.0.1 -e "CREATE USER voluble_test@127.0.0.1 IDENTIFIED BY 'volubletest';"
    - mysql -uroot -ppa55w0rd -P3306 -h127.0.0.1 -e "GRANT ALL PRIVILEGES ON voluble_test.* TO 'voluble_test'@'127.0.0.1';"
    - mysql -uroot -ppa55w0rd -P3306 -h127.0.0.1 -e "FLUSH PRIVILEGES;"

  test_script: npm test
