container:
  image: node:latest

test_task:
  global_clis_script:
    - npm install -G typescript mocha

  node_modules_cache:
    folder: node_modules
    fingerprint_script: cat package-lock.json
    populate_script: npm ci

  build_script:
    - tsc -v;
    - tsc

  test_script:
    - npm test
